#!/usr/bin/python
'''LAPS for macOS devices
__________________________________________________________________________
| This python script will set a randomly generated password for your     |
| local adminsitrator account on macOS if the expiration date has passed |
| in your Active Directory. The results will then be written to your AD  |
| into the attribute dsAttrTypeNative:ms-Mcs-AdmPwd to mimic the same    |
| behavior of Local Administrator Password Solution (LAPS) on Windows.   |
| Once completed, an expiration date will then be set for the new        |
| password and written to the AD attribute dsAttrTypeNative:ms-Mcs-      |
| AdmPwdself.expirationTime. This will allow the LAPS UI to be utilized  |
| and the random password the ability to be seen by those with permission|
| to retrieve it.                                                        |
|________________________________________________________________________|
Joshua D. Miller - josh@psu.edu - The Pennsylvania State University
Script was Last Updated July 14, 2016'''
# pylint: disable=C0103
from __future__ import print_function
from datetime import datetime, timedelta
from string import ascii_letters, punctuation, digits
from time import mktime
import logging
import random
# pylint: disable=E0611
from Foundation import CFPreferencesCopyAppValue
from OpenDirectory import ODSession, ODNode, kODRecordTypeComputers, \
    kODRecordTypeUsers
from SystemConfiguration import SCDynamicStoreCreate, \
    SCDynamicStoreCopyValue


class macOSLAPS(object):
    '''main class of application'''
    # Current time
    now = datetime.now()
    # Preference Variables
    bundleid = 'edu.psu.macoslaps'
    defaultpreferences = {
        'LocalAdminAccount': 'admin',
        'PasswordLength': 12,
        'DaysTillExpiration': 60
    }
    # Active Directory Attributes
    adpath = ''
    computerpath = ''
    expirationtime = ''
    lapsattributes = dict()
    computer_record = None
    # Setup Logging
    logging.basicConfig(filename='/Library/Logs/macOSLAPS.log',
                        level=logging.DEBUG,
                        format='%(asctime)s|%(levelname)s:%(message)s')

    def get_config_settings(self, preference_key):
        '''Function to retrieve configuration settings from
        /Library/Preferences or /Library/Managed Preferences
        '''
        preference_file = self.bundleid
        preference_value = CFPreferencesCopyAppValue(preference_key,
                                                     preference_file)
        if preference_value is None:
            preference_value = self.defaultpreferences.get(preference_key)
        return preference_value

    def connect_to_ad(self):
        '''Function to connect and pull information from Active Directory
        some code borrowed from AD PassMon - Thanks @macmuleblog'''
        # Active Directory Connection and Extraction of Data
        # Code borrowed from AD PassMon to get AD info
        try:
            # Create Net Config
            net_config = SCDynamicStoreCreate(None, "net", None, None)
            # Get Active Directory Info
            ad_info = dict(
                SCDynamicStoreCopyValue(
                    net_config, 'com.apple.opendirectoryd.ActiveDirectory'))
            # Create Active Directory Path
            self.adpath = '{0:}/{1:}'.format(ad_info['NodeName'],
                                             ad_info['DomainNameDns'])
            # Computer Path
            self.computerpath = 'Computers/{0:}'.format(
                                ad_info['TrustAccount'])
            # Use Open Directory To Connect to Active Directory
            node, error = ODNode.nodeWithSession_name_error_(
                ODSession.defaultSession(), self.adpath, None)
            # Grab the Computer Record
            self.computer_record, error = node.\
                recordWithRecordType_name_attributes_error_(
                    kODRecordTypeComputers, ad_info
                    ['TrustAccount'], None, None)
            # Convert to Readable Values
            values, error = self.computer_record.\
                recordDetailsForAttributes_error_(None, None)
            # LAPS Attributes
            self.lapsattributes[0] = 'dsAttrTypeNative:ms-Mcs-AdmPwd'
            self.lapsattributes[1] = \
                'dsAttrTypeNative:ms-Mcs-AdmPwdExpirationTime'
            # Get Expiration Time of Password
            try:
                self.expirationtime = values[self.lapsattributes[1]]
            except Exception:
                logging.info('There has never been a random password generated'
                             ' for this device. Setting a default expiration'
                             ' date of 01/01/2001 in Active Directory to'
                             ' force a password change...')
                self.expirationtime = '126227988000000000'
        # pylint: disable=W0703
        except Exception as error:
            logging.error(error)
            exit(1)

    @staticmethod
    def make_random_password(length):
        '''Generate a Random Password
        Thanks Mike Lynn - @frogor'''
        # Characters used for random password
        characters = ascii_letters + punctuation + digits
        password = []
        for i in range(length):
            password.insert(i, random.choice(characters))
        return ''.join(password)

    def windows_epoch_time_converter(self, time_type, expires):
        '''Convert from Epoch to Windows or from Windows
        to Epoch - Thanks Rusty Myers for determine Windows vs.
        Epoch Time @rustymyers'''
        if time_type == 'epoch':
            # Convert Windows Time to Epoch Time
            format_expiration_time = int(self.expirationtime[0])\
                / 10000000 - 11644473600
            format_expiration_time = datetime.fromtimestamp(
                format_expiration_time)
            return format_expiration_time
        elif time_type == 'windows':
            # Convert the time back from Time Stamp to Epoch to Windows
            # and add 30 days onto the time
            new_expiration_time = (self.now + timedelta(days=expires))
            formatted_new_expiration_time = new_expiration_time
            new_expiration_time = new_expiration_time.timetuple()
            new_expiration_time = mktime(new_expiration_time)
            new_expiration_time = ((new_expiration_time + 11644473600) *
                                   10000000)
            return (new_expiration_time, formatted_new_expiration_time)

    def password_check(self):
        '''Perform a password check and change the local
        admin password and write it to Active Directory if
        needed - Thanks to Tom Burgin and Ben Toms
                           @tomjburgin, @macmuleblog'''
        local_admin = LAPS.get_config_settings('LocalAdminAccount')
        exp_days = LAPS.get_config_settings('DaysTillExpiration')
        pass_length = LAPS.get_config_settings('PasswordLength')
        password = LAPS.make_random_password(pass_length)
        formatted_expiration_time = \
            LAPS.windows_epoch_time_converter('epoch', exp_days)
        # Determine if the password expired and then change it
        if formatted_expiration_time < self.now:
            # Log that the password change is being started
            logging.info('Password change required.'
                         ' Performing password change...')
            try:
                # Set new random password in Active Directory
                self.computer_record.setValue_forAttribute_error_(
                    password, self.lapsattributes[0], None)
                # Change the local admin password
                logging.info('Setting random password for local'
                             ' admin account %s...', local_admin)
                # Connect to Local Node
                local_node, error = ODNode.nodeWithSession_name_error_(
                    ODSession.defaultSession(), '/Local/Default', None)
                # Pull Local Administrator Record
                local_admin, error = local_node.\
                    recordWithRecordType_name_attributes_error_(
                        kODRecordTypeUsers, local_admin, None, None)
                # Change the password for the account
                local_admin.changePassword_toPassword_error_(
                    None, password, None)
                # Convert Time to Windows Time to prepare
                # for new expiration time to be written to AD
                new_expires = dict()
                new_expires[0], new_expires[1] = LAPS.\
                    windows_epoch_time_converter('windows', exp_days)
                # Set the Expiration Time to 30 days from now in AD
                self.computer_record.setValue_forAttribute_error_(
                    str(int(new_expires[0])), self.lapsattributes[1], None)
                logging.info('Password change has been completed. '
                             'New expiration date is %s',
                             new_expires[1])
            # pylint: disable=W0703
            except Exception as error:
                logging.error(error)
                exit(1)
        else:
            # Log that a password change is not necessary at this time
            logging.info('Password change not necessary at this time as'
                         ' the expiration date is %s',
                         formatted_expiration_time)
            exit(0)

LAPS = macOSLAPS()
LAPS.connect_to_ad()
LAPS.password_check()
